### ISSUE TITLE
Game Crashing for gold village

### ISSUE THREAD

**Issue by RefilmGaming** [DatJaneDoe/GoldVillage#1]
The mod loads fine i can double click on tower to see the paths and what not but the second I go to try to place it my game crashes

**Comment by digga2323232323** [comment]
downgrade MelonLoader from current latest (v0.6.4.) to v0.6.1. well that what helped me

**Comment by digga2323232323** [comment]
Well i hope that helps you

**Comment by DatJaneDoe** [comment]
Gold Village broke in V44. It was just fixed

**Comment by heretocomment1** [comment]
crashes my game

**Comment by heretocomment1** [comment]
when registering content
![Screenshot 2024-10-03 193051](https://github.com/user-attachments/assets/b8019c0f-04e4-406a-b68c-ad9d9e10b5ca)
 content

**Comment by ShikuTeshi** [comment]
It sort of works for me on MelonLoader 0.6.6

But once you get upgrades that give the village some active abilities it begins to spit out so many error messages into MelonLoader that it slows down the game dramatically. From this point it quickly enters a loop that causes the game to malfunction with many unintended affects such as inability to quit the game normally or resume at a later time. Freshly placed towers can't be interacted with and as a result can't be upgraded.

Otherwise just having the mod installed doesn't seem to cause any problems. It only starts to malfunction when a village obtains an active ability.

**Comment by pyradyne** [comment]
gotten the v48 of tsg village and installed within the game. isolated the village mod to be by itself and the story is still the same. upgrading it, will work ok but when selling or clicking with the village upgraded spits out a lot of error messages on melon loader. selling it will break the game entirely, no new monkeys can be placed, sold. you are able to interact with the ui and attempt to exit to home, it will lead you to a long/infinite loading screen. i have attempted to downgrade melonloaders versions. nothing seems to come out of it
